export const REQUEST_ACADEMIC_LEVELS = 'REQUEST_ACADEMIC_LEVELS';
export const REQUEST_ACADEMIC_LEVELS_SUCCESS = 'REQUEST_ACADEMIC_LEVELS_SUCCESS';
export const REQUEST_ACADEMIC_LEVELS_FAIL = 'REQUEST_ACADEMIC_LEVELS_FAIL';